name: Code Quality

on:
  - pull_request
  - push

jobs:
  coding-guidelines:
    name: Coding Guidelines (php-cs-fixer)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Instal PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: php-cs-fixer:2.16.3

      - name: Run friendsofphp/php-cs-fixer
        run: php-cs-fixer fix --diff-format=udiff --dry-run --show-progress=dots --using-cache=no --verbose

  type-checker:
    name: Type Checker (vimeo/psalm)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: composer:v1, psalm:3.16

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Run vimeo/psalm on packages
        run: psalm --no-progress --shepherd --show-info=false --stats
