name: Dependencies

on:
  - pull_request
  - push

jobs:
  monorepo_testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        php-version:
          - 7.4
        dependencies:
          - lowest
          - highest

    name: phpunit-extensions (${{ matrix.os }}:PHP-${{ matrix.php-version }}:${{ matrix.dependencies }})
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - if: matrix.dependencies == 'highest'
        run: |
          composer update --no-interaction --no-progress --no-ansi

      - if: matrix.dependencies == 'lowest'
        run: |
          composer update --no-interaction --no-progress --no-ansi --prefer-lowest

      - name: Run composer-require-checker --config-file=.composer-require-checker.json
        uses: docker://webfactory/composer-require-checker:latest
        with:
          args: --config-file=.composer-require-checker.json



  after_split_testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        package_name:
          - phpunit-arrays
          - phpunit-common
          - phpunit-inheritance
          - phpunit-regexp
          - phpunit-properties
        os:
          - ubuntu-latest
        php-version:
          - 7.4
        dependencies:
          - lowest
          - highest

    name: ${{ matrix.package_name }} (${{ matrix.os }}:PHP-${{ matrix.php-version }}:${{ matrix.dependencies }})

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - run: |
          composer update --no-interaction --no-progress --no-ansi
          vendor/bin/monorepo-builder localize-composer-paths --ansi

      - if: matrix.dependencies == 'highest'
        run: |
          cd packages/${{ matrix.package_name }}
          composer update --no-interaction --no-progress --no-ansi

      - if: matrix.dependencies == 'lowest'
        run: |
          cd packages/${{ matrix.package_name }}
          composer update --no-interaction --no-progress --no-ansi --prefer-lowest

      - name: Run composer-require-checker --config-file=.composer-require-checker.json
        uses: docker://webfactory/composer-require-checker:latest
        with:
          args: --config-file=.composer-require-checker.json
          volume: "./packages/${{ matrix.package_name }}:/app ./.composer-require-checker.json:/app/.composer-require-checker.json"
