name: Unit Tests

on:
  - pull_request
  - push

jobs:
  monorepo_testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php-version:
          - 7.3
          - 7.4
          - 8.0
        dependencies:
          - lowest
          - highest

    name: phpunit-extensions (${{ matrix.os }}:PHP-${{ matrix.php-version }}:${{ matrix.dependencies }})
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - if: matrix.dependencies == 'highest'
        run: |
          composer update --no-interaction --no-progress --no-ansi

      - if: matrix.dependencies == 'lowest'
        run: |
          composer update --no-interaction --no-progress --no-ansi --prefer-lowest

      - run: |
          vendor/bin/phpunit

      - name: Send code coverage report to Codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  after_split_testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        package_name:
          - phpunit-common
          - phpunit-inheritance
          - phpunit-pcre
          - phpunit-properties
        os:
          - ubuntu-latest
        php-version:
          - 7.3
          - 7.4
          - 8.0
        dependencies:
          - highest

    name: ${{ matrix.package_name }} (${{ matrix.os }}:PHP-${{ matrix.php-version }}:${{ matrix.dependencies }})

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - run: |
          composer update --no-interaction --no-progress --no-ansi
          vendor/bin/monorepo-builder localize-composer-paths --ansi

      - if: matrix.dependencies == 'highest'
        run: |
          cd packages/${{ matrix.package_name }}
          composer update --no-interaction --no-progress --no-ansi

      - if: matrix.dependencies == 'lowest'
        run: |
          cd packages/${{ matrix.package_name }}
          composer update --no-interaction --no-progress --no-ansi --prefer-lowest

      - run: |
          cd packages/${{ matrix.package_name }}
          vendor/bin/phpunit --no-coverage

