name: Unit Testing

on:
  - pull_request
  - push

jobs:
  monorepo_testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php-version:
          - 7.3
          - 7.4
          - 8.0
        dependencies:
          - lowest
          - highest

    name: phpunit-extensions (${{ matrix.os }}:PHP-${{ matrix.php-version }})
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - if: matrix.dependencies == 'highest'
      - run: |
          composer update --no-interaction --no-progress --no-ansi

      - if: matrix.dependencies == 'lowest'
      - run: |
          composer update --no-interaction --no-progress --no-ansi --prefer-lowest

      - run: |
          vendor/bin/phpunit --no-coverage

  after_split_testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        package_name:
          - phpunit-common
          - phpunit-inheritance
          - phpunit-pcre
          - phpunit-properties
        os:
          - ubuntu-latest
          - windows-latest
        php-version:
          - 7.3
          - 7.4
          - 8.0
        dependencies:
          - lowest
          - highest

    name: ${{ matrix.package_name }} (${{ matrix.os }}:PHP-${{ matrix.php-version }}:${{ matrix.dependencies }})

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - if: matrix.dependencies == 'highest'
        run: |
          composer update --no-interaction --no-progress --no-ansi
          vendor/bin/monorepo-builder localize-composer-paths --ansi

          cd packages/${{ matrix.package_name }}
          composer update --no-interaction --no-progress --no-ansi

      - if: matrix.dependencies == 'lowest'
        run: |
          composer update --no-interaction --no-progress --no-ansi --prefer-lowest
          vendor/bin/monorepo-builder localize-composer-paths --ansi --prefer-lowest

          cd packages/${{ matrix.package_name }}
          composer update --no-interaction --no-progress --no-ansi

      - run: |
          cd packages/${{ matrix.package_name }}
          vendor/bin/phpunit --no-coverage

